### ISSUE TITLE
All highlight seems broken

### ISSUE THREAD

**Issue by zraffer** [tree-sitter/tree-sitter-agda#9]
(After performing a fresh install of fresh Atom and the current `language-agda` plugin)
See all highlight in a strange new look. Reproducible in tree-sitter mode only.
Versions:
```
$ find .atom -name '*tree-sitter-agda*'
.atom/.apm/_prebuilds/ccb761-tree-sitter-agda-v1.1.0-electron-v64-linux-x64.tar.gz
.atom/packages/language-agda/grammars/tree-sitter-agda.cson
.atom/packages/language-agda/node_modules/tree-sitter-agda

$ rpm -aq atom
atom-1.39.0-0.1.x86_64
```

screenshot: https://gist.github.com/zraffer/f13cdf3da1fff8aa8f251542fc9ccea7#file-screenshot-png

**Comment by banacorn** [comment]
Thank you for reporting this!

**Comment by banacorn** [comment]
Blocked by https://github.com/tree-sitter/tree-sitter/issues/314, I'll see if I can get pass it (by reverting changes related to it)

**Comment by zraffer** [comment]
After updating to `tree-sitter-agda-v1.1.1-electron-v64-linux-x64.tar.gz` the old good highlight was restored, thank you. But now I've faced to an error from `agda-mode`, which I'll file there as an issue.

**Comment by banacorn** [comment]
The `v1.1.1` patch falls back to old way of parsing grammar (using regular expressions XD), so you may notice that the highlighting looks a lot worse than it should be.
I'm gonna see if I can fix the tree-sitter parser and get it back on `v.1.1.2`

Edit: @rafeca did `v1.1.1` really worked? Is the highlighting as colorful as in the [Readme](https://github.com/tree-sitter/tree-sitter-agda/blob/master/README.md), or do you see just 1 or 2 colors? Because I still can't get `v64` working on my machine.

**Comment by zraffer** [comment]
It is colorful for me (Fedora 30 x64), but a few big files is colored only at the first half, the other part of file being white.

**Comment by banacorn** [comment]
The half being white problem should be related to unicode symbols.

It's an issue from the tree-sitter parser itself. We tried to workaround that issue but then we encountered more issues from tree-sitter. Yeah, I should open an issue bout that.

**Comment by zraffer** [comment]
Looking forward for technology improvement! Thank you.
